### ISSUE TITLE
Plugin issues and ThreadStateException

### ISSUE THREAD

**Issue by haato3o** [Kaedras/HunterPie-SyncPlugin#1]
I've taken a quickly look at the plugin code and found some issues:

### Unload

In the `Unload` function, you're hooking the events again instead of unhooking them

https://github.com/Kaedras/HunterPie-SyncPlugin/blob/0784c4ca24e51cfc22e9ada656f7827219281216/main.cs#L174
https://github.com/Kaedras/HunterPie-SyncPlugin/blob/0784c4ca24e51cfc22e9ada656f7827219281216/main.cs#L178

### GameScanDelay workaround

I'm not really sure why you're editing the game scan delay or what that workaround is for, but you should never change the scan delay like that, the overlay and some features depends on a low delay to work properly and this plugin is breaking it.

https://github.com/Kaedras/HunterPie-SyncPlugin/blob/0784c4ca24e51cfc22e9ada656f7827219281216/main.cs#L517

## ThreadStateException

I've been getting some crash logs recently due to `System.Threading.ThreadStateException` caused by this plugin, so might be worth it to take a look into it if you have time.

```
System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartupSetApartmentStateInternal()
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start()
   at HunterPie.Plugins.SyncPlugin.startSyncThread()
   at HunterPie.Plugins.SyncPlugin.<InitializeSessionAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
````

**Comment by Kaedras** [comment]
Hi, thanks for the report. I've put the server into maintenance mode to effectively disable the plugin until I've had time to resolve the issues. I will also change the description to better reflect the current status of the plugin.

**Comment by Kaedras** [comment]
I just released an update, the plugin should be working now, but I haven't been able to properly test the client side yet, so I'll keep the issue open for now.
